name: Build and Deploy Spring app

#specify when to trigger ur pipeline actions
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Unit Tests
        run: mvn -B test --file pom.xml

        # package and build ur application
      - name: Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml

          # pushing to docker
        # You need to replace this with your own dockerhub credentials
      - run:
        name: Authenticate to Docker Hub






